### ISSUE TITLE
Some related work

### ISSUE THREAD

**Issue by Chen-Yang-Liu** [usail-hkust/Awesome-Urban-Foundation-Models#2]
**This repository is very good!! I found some related work:**

(1) Remote Sensing Vision-Language Foundation Models:
- PromptCC: **A Decoupling Paradigm with Prompt Learning for Remote Sensing Image Change Captioning** [[paper]](https://ieeexplore.ieee.org/document/10271701) [[code]](https://github.com/Chen-Yang-Liu/PromptCC)
  - Liu C, Zhao R, Chen J, et al.
  - (2023.10) IEEE Transactions on Geoscience and Remote Sensing
 
(2) Remote Sensing Agents:
- **Change-Agent: Toward Interactive Comprehensive Remote Sensing Change Interpretation and Analysis** [[paper]](https://ieeexplore.ieee.org/abstract/document/10591792) [[code]](https://github.com/Chen-Yang-Liu/Change-Agent)
  - (2024. 03) IEEE Transactions on Geoscience and Remote Sensing

**Comment by zhaoxu98** [comment]
Thanks for your suggestions! We will add these works to our repo and paper :) 
@jhanao-hkust

**Comment by hanjindong** [comment]
Thanks for your suggestion! We’ve added these references to the repository and will consider including them in the next version of our paper.
